server:
  port: 8080

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:${db.name}
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true